spring.application.name=backend
spring.datasource.url=jdbc:h2:mem:donworrydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# AI Server Settings
ai.server.base-url=https://do-a681cf6dd6d14b5f895f332482837eeb.ecs.ap-northeast-2.on.aws
ai.server.token=donworry-local-test-2026
ai.server.timeout=10